repos:
  - repo: https://github.com/Calinou/pre-commit-luacheck
    rev: v1.0.0
    hooks:
      - id: luacheck
  - repo: local
    hooks:
      - id: alejandra
        name: Alejandra
        language: system
        entry: alejandra
        types: [nix]
      - id: stylua
        name: StyLua
        language: system
        entry: stylua
        args: [--respect-ignores]
        types: [lua]
